"""
state.py

Shared workflow state used by all LangGraph agents.

Each agent reads from and updates this shared state.
"""

from typing import TypedDict


class AgentState(TypedDict):
    """
    Shared state passed between all LangGraph agents.
    """

    # Customer question
    question: str

    # Intent detected by Intent Agent
    intent: str

    # Context retrieved by Knowledge Agent
    retrieved_context: str

    # Draft response generated by Advisor Agent
    draft_response: str

    # Final validated response
    final_response: str

    # Additional workflow metadata
    metadata: dict

    # Error information (if any)
    error: str